name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Continuous Delivery - Upload JS files
        uses: actions/upload-artifact@v4
        with:
          name: projetozip
          path: "**/*.js"

  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensagem para o Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🚀 Novo commit feito na branch **main**!"
