namwe: Continuos Integration

on: [push, pull_request]

jobs: 
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Using Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: run install
        run: |
        npm install
        npm run build